
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// ACCOUNT
export const RESET_ACCOUNT = "RESET_ACCOUNT";
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS";
export const LIST_ACCOUNT_SUCCESS = "LIST_ACCOUNT_SUCCESS";
export const UPDATE_ACCOUNT_SUCCESS = "UPDATE_ACCOUNT_SUCCESS";

// TX
export const RESET_TX = "RESET_TX";
export const CREATE_TX_SUCCESS = "CREATE_TX_SUCCESS";
export const DELETE_TX_SUCCESS = "DELETE_TX_SUCCESS";
export const FINDBYACCOUNT_ID_TX_SUCCESS = "FINDBYACCOUNT_ID_TX_SUCCESS";
export const GET_TX_SUCCESS = "GET_TX_SUCCESS";
export const LIST_TX_SUCCESS = "LIST_TX_SUCCESS";
export const UPDATE_TX_SUCCESS = "UPDATE_TX_SUCCESS";

// USER
export const RESET_USER = "RESET_USER";
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const FINDBYUSER_ACCOUNTS_USER_SUCCESS = "FINDBYUSER_ACCOUNTS_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// CUSTOMER_ACCOUNT
export const RESET_CUSTOMER_ACCOUNT = "RESET_CUSTOMER_ACCOUNT";
export const CREATE_CUSTOMER_ACCOUNT_SUCCESS = "CREATE_CUSTOMER_ACCOUNT_SUCCESS";
export const DELETE_CUSTOMER_ACCOUNT_SUCCESS = "DELETE_CUSTOMER_ACCOUNT_SUCCESS";
export const FINDBYACCOUNT_ID_CUSTOMER_ACCOUNT_SUCCESS = "FINDBYACCOUNT_ID_CUSTOMER_ACCOUNT_SUCCESS";
export const GET_CUSTOMER_ACCOUNT_SUCCESS = "GET_CUSTOMER_ACCOUNT_SUCCESS";
export const LIST_CUSTOMER_ACCOUNT_SUCCESS = "LIST_CUSTOMER_ACCOUNT_SUCCESS";
export const UPDATE_CUSTOMER_ACCOUNT_SUCCESS = "UPDATE_CUSTOMER_ACCOUNT_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
